### PR TITLE
added funeral march

### PR DESCRIPTION
**Pull request by danyshaanan**
If there is a problem with the way I've encoded the song, I can replace it with the actual array.

### CODE REVIEW

**Comment by BrianGenisio** [comment]
I like this song representation.  I kind of think it should be supported in the J5 Piezo `song()` implementation, but allow for the octave notation OR default to 4th octave if it doesn't exist.

#cc @rwaldron

**Comment by BrianGenisio** [comment]
If not, moving this helper into this project so it is common and re-usable would be nice.

**Comment by danyshaanan** [comment]
@rwaldron : If you too like the idea, say so and I'll take a shot at working it cleanly into johnny-five.

@BrianGenisio ...and if not, I could make it reusable within j5-songs.

#cc @ganimomer

**Comment by rwaldron** [comment]
Seems good to me!

**Comment by danyshaanan** [comment]
Conflict with the jingle-bells PR resolved.

String encoding in johnny-five coming soon.

**Comment by danyshaanan** [comment]
@julianduque Can this be merged, or is there anything else that should be done here?

**Comment by julianduque** [comment]
@danyshaanan merged and published, thanks!!

**Comment by danyshaanan** [comment]
Thanks! :]

**Pull request merged**
